/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ClipBoard: typeof import('./src/components/ClipBoard/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue')['default']
    LayoutCenterPanel: typeof import('./src/components/Layout/CenterPanel.vue')['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
    LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue')['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue')['default']
    NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue')['default']
    NavigationNavSideBar: typeof import('./src/components/Navigation/NavSideBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    NSpin: typeof import('naive-ui')['NSpin']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
    TableList: typeof import('./src/components/TableList/index.vue')['default']
  }
}
