/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ClipBoard: typeof import('./src/components/ClipBoard/index.vue')['default']
    CustomTooltip: typeof import('./src/components/CustomTooltip/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue')['default']
    LayoutCenterPanel: typeof import('./src/components/Layout/CenterPanel.vue')['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
    LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue')['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue')['default']
    NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue')['default']
    NavigationNavSideBar: typeof import('./src/components/Navigation/NavSideBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
    TableList: typeof import('./src/components/TableList/index.vue')['default']
  }
}

// For TSX support
declare global {
  const 404: typeof import('./src/components/404.vue')['default']
  const ClipBoard: typeof import('./src/components/ClipBoard/index.vue')['default']
  const CustomTooltip: typeof import('./src/components/CustomTooltip/index.vue')['default']
  const IconFont: typeof import('./src/components/IconFont/index.vue')['default']
  const IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue')['default']
  const LayoutCenterPanel: typeof import('./src/components/Layout/CenterPanel.vue')['default']
  const LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
  const LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue')['default']
  const LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
  const LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
  const MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
  const NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
  const NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue')['default']
  const NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue')['default']
  const NavigationNavSideBar: typeof import('./src/components/Navigation/NavSideBar.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NEllipsis: typeof import('naive-ui')['NEllipsis']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NFloatButton: typeof import('naive-ui')['NFloatButton']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NInput: typeof import('naive-ui')['NInput']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NResult: typeof import('naive-ui')['NResult']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const Pagination: typeof import('./src/components/Pagination/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
  const TableList: typeof import('./src/components/TableList/index.vue')['default']
}